
<div class="owl-carousel main-page-slider owl-theme slider-first">
  <div><img  src="<?php echo $this->getViewFileUrl("images/main-image.png");?> " /></div>
  <div><img  src="<?php echo $this->getViewFileUrl("images/main-image.png");?> " /></div>
  <div><img  src="<?php echo $this->getViewFileUrl("images/main-image.png");?> " /></div>
</div>


<script>
   require([
       'jquery',
       'owlcarousel'
   ], function ($) {
       //'use strict';
       //jQuery.noConflict();
       $(".main-page-slider").owlCarousel({
           //nav: true, // Show next and prev buttons
           //navText:["previous","next"], //show prev next
           loop: true,
           dots:false,
           autoplay: true, //Set AutoPlay
           autoplayHoverPause: true, //stop when mouse on carousel
           items : 1
       });
   });
</script>